# Generated by Django 3.1.6 on 2023-10-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_txt',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_txt',
            new_name='question_text',
        ),
    ]
